### ISSUE TITLE
Weapon icon looks like upside down cross

### ISSUE THREAD

**Issue by RyanFleck** [shahiro770/CandleLight#26]
![image](https://user-images.githubusercontent.com/28709508/86862141-9d9a8b80-c096-11ea-9b9a-7ebbedcbc2aa.png)

...and Priscilla lost all her health. Otherwise, great progression!

Was impressed with how the inventory automatically switches depending on what you're about to pick up.

You can delete this issue, I just wanted to say hello.

**Comment by shahiro770** [comment]
Hey Ryan! I miss you.
